### PR TITLE
Python 3.8 port

### PR DESCRIPTION
**Pull request by rvhonorato**
This PR ports the python code to v3.8 and also adds example data derived from a Haddock run of _2oob_ with cm-restraints, the example data is compressed (`.gz` ~4.3Mb) and instructions are provided on how to run it.

### CODE REVIEW

**Comment by amjjbonvin** [comment]
Did you create a new branch for it?

Remember fcc is used but the 2.4 server and there we still use python2.7.
Might get messy to mix python versions.

**Comment by amjjbonvin** [comment]
PS: In order for HADDOCK to start using this (or the python2 version of the main fcc code we need the -H option currently implemented in the version found in the tools directory of haddock2.4

This will write MTX_DONE once the clustering has been successful. And this is monitored by haddock

**Comment by JoaoRodrigues** [comment]
Thanks @rvhonorato but I would put this in a separate branch. I was supposed to have a student help me this summer porting this to Python 3 but it never happened. It's on my to do list though. The goal of my Python 3 port is not only to make it work on Py3 but also to make it more efficient and simpler to install/use.

**Comment by rvhonorato** [comment]
> @amjjbonvin: Did you create a new branch for it?

> @JoaoRodrigues: Thanks @rvhonorato but I would put this in a separate branch

I cannot create a branch here, that's why the PR is on the master. Yes this **must** be a branch! 

I was doing some work on a weekend project and for that I'll use the python3 port of fcc. Since I have already done the port, figured it might be useful here! But if at the moment is not, also fine! ;)

**Comment by JoaoRodrigues** [comment]
Oh, I see. I'll push this to a branch then!

**Comment by JoaoRodrigues** [comment]
Done! fcc/python3

I'll work on the redo branch this month.

**Pull request closed without merging**
